Classify the email using the binary classification method. Email Spam detection has two
states: a) Normal State Not Spam, b) Abnormal State Spam. Use K-Nearest Neighbors
and Support Vector Machine for classification. Analyze their performance.
Dataset link: The emails.csv dataset on the Kaggle
https://www.kaggle.com/datasets/balaka18/email-spam-classification-dataset-csv

In [29]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv('emails.csv')
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay   
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0  \
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [31]:
df.head()
df.info()
df.columns
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB


Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [32]:
df.dropna(inplace=True)

In [33]:
df = df.drop(['Email No.'],axis=1)

In [34]:
x = df.drop(['Prediction'],axis=1)
y = df['Prediction']

In [35]:
from sklearn.preprocessing import scale
x = scale(x)

In [36]:
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

KNN Classifier

In [37]:
from sklearn.neighbors import KNeighborsClassifier 

knn = KNeighborsClassifier()

knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

In [38]:
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,accuracy_score,classification_report
print("\nKNN Classifier Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# cnf = confusion_matrix(y_test,y_pred)
# cm = ConfusionMatrixDisplay(confusion_matrix=cnf,display_labels=['Spam','Not Spam'])

# cm.plot()
# plt.show()


KNN Classifier Performance:
Accuracy: 0.8208762886597938
Confusion Matrix:
 [[842 255]
 [ 23 432]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.77      0.86      1097
           1       0.63      0.95      0.76       455

    accuracy                           0.82      1552
   macro avg       0.80      0.86      0.81      1552
weighted avg       0.87      0.82      0.83      1552



SVM

In [39]:
from sklearn.svm import SVC 

model = SVC()

model.fit(x_train,y_train)
y_pred_svm = model.predict(x_test)
y_pred_svm

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [40]:
print("\nSVM Classifier Performance:")
print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("Classification Report:\n", classification_report(y_test, y_pred_svm))


SVM Classifier Performance:
Accuracy: 0.9381443298969072
Confusion Matrix:
 [[1091    6]
 [  90  365]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.99      0.96      1097
           1       0.98      0.80      0.88       455

    accuracy                           0.94      1552
   macro avg       0.95      0.90      0.92      1552
weighted avg       0.94      0.94      0.94      1552

