Given a bank customer, build a neural network-based classifier that can determine
whether they will leave or not in the next 6 months.
Dataset Description: The case study is from an open-source dataset from
Kaggle.The dataset contains 10,000 sample points with 14 distinct features
such as CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance,
etc.
Link to the Kaggle project:
https://www.kaggle.com/barelydedicated/bank-customer-churnmodeling Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test
sets.
3. Normalize the train and test data.
4. Initialize and build the model. Identify the points of improvement and implement the
same.
Print the accuracy score and confusion matrix (5 points).

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Tanmay49/SEM7/main/ML/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age   
0          1    15634602  Hargrave          619    France  Female   42  \
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember   
0       2       0.00              1          1               1  \
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
gender = pd.get_dummies(df['Gender'],drop_first=True)
geography = pd.get_dummies(df['Geography'],drop_first=True)
df = pd.concat([df,gender,geography],axis=1)
df = df.drop(columns=['Gender','Geography'],axis=1)
df = df.dropna()
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard   
0             619   42       2       0.00              1          1  \
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited   Male  Germany  Spain  
0                  1        101348.88       1  False    False  False  
1                  1        112542.58       0  False    False   True  
2                  0        113931.57       1  False    False  False  
3                  0         93826.63       0  False    False  False  
4                  1         79084.10       0  False    False   True  
...              ...              ...     ...    ...      ...    ...  
9995               0         96270.64       0   True    False  False  
9996               1        101699.77       0   True    False  False  
9997               1         42085.58       1  False    False  False  
9998               0         92888.52       1   True     True  False  
9999               0         38190.78       0  False    False  False  

[10000 rows x 12 columns]

In [6]:
x = df.drop(['Exited'],axis=1)
y = df['Exited']

In [8]:
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler()
x = sc.fit_transform(x)
x 

array([[-0.32622142,  0.29351742, -1.04175968, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.09598752,
        -0.57873591,  1.74273971],
       [-1.53679418,  0.29351742,  1.03290776, ..., -1.09598752,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.91241915,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -1.09598752,
        -0.57873591, -0.57380915]])

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3,random_state=42)

In [10]:
!pip install tensorflow

You should consider upgrading via the 'C:\python37\python.exe -m pip install --upgrade pip' command.


In [11]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [12]:
model = Sequential()
model.add(Dense(activation='relu',units=6))
model.add(Dense(activation='relu',units=6))
model.add(Dense(activation='sigmoid',units=1))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=10,epochs=50)

Epoch 1/50
700/700 [==============================] - 5s 3ms/step - loss: 0.5324 - accuracy: 0.7884
Epoch 2/50
700/700 [==============================] - 2s 4ms/step - loss: 0.4634 - accuracy: 0.7924
Epoch 3/50
700/700 [==============================] - 3s 4ms/step - loss: 0.4437 - accuracy: 0.7924
Epoch 4/50
700/700 [==============================] - 2s 2ms/step - loss: 0.4348 - accuracy: 0.7981
Epoch 5/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4279 - accuracy: 0.8094
Epoch 6/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4204 - accuracy: 0.8209
Epoch 7/50
700/700 [==============================] - 3s 4ms/step - loss: 0.4134 - accuracy: 0.8261
Epoch 8/50
700/700 [==============================] - 4s 5ms/step - loss: 0.4067 - accuracy: 0.8276
Epoch 9/50
700/700 [==============================] - 3s 5ms/step - loss: 0.4007 - accuracy: 0.8320
Epoch 10/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3946 - accuracy: 0.8354

In [13]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5).astype(int)
y_pred

94/94 [==============================] - 0s 1ms/step


array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8693333333333333
[[2318   98]
 [ 294  290]]
